# Generated by Django 2.1 on 2018-08-22 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelloWorld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldone', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(default='', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('personal_website', models.URLField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('about', models.CharField(blank=True, default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_app.Users')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('remote', models.BooleanField(default=False)),
                ('relocate', models.BooleanField(default=False)),
                ('linkedin', models.URLField(blank=True, default='')),
                ('github', models.URLField(blank=True, default='')),
                ('twitter', models.URLField(blank=True, default='')),
                ('codepen', models.URLField(blank=True, default='')),
                ('portfolio_picture', models.URLField(blank=True, default='')),
                ('joined_field', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='django_app.HelloWorld')),
            ],
            bases=('django_app.users',),
        ),
        migrations.CreateModel(
            name='Hire_Partners',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_app.Users')),
                ('company_name', models.CharField(blank=True, default='', max_length=50)),
            ],
            bases=('django_app.users',),
        ),
    ]
