# Generated by Django 2.1 on 2018-08-21 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employerName', models.CharField(default='', max_length=50, unique=True)),
                ('currentlySubscribed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EmployerFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='JobListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionTitle', models.CharField(max_length=400)),
                ('postTime', models.CharField(max_length=400)),
                ('remote', models.BooleanField(default=False)),
                ('employerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400)),
                ('postTime', models.CharField(max_length=400)),
                ('employerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('linkedIn', models.CharField(default='', max_length=50)),
                ('twitter', models.CharField(default='', max_length=50)),
                ('github', models.CharField(default='', max_length=50)),
                ('relocate', models.BooleanField(default=False)),
                ('remote', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.Employer')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.User'),
        ),
        migrations.AddField(
            model_name='messages',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.Student'),
        ),
        migrations.AddField(
            model_name='employerfavorites',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.Student'),
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.User'),
        ),
    ]
