# Generated by Django 2.1 on 2018-09-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_listing',
            name='clients',
        ),
    ]
