# Generated by Django 2.1 on 2018-08-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='companyWebsite',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='codepen',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='personalWebsite',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedIn',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
