# Generated by Django 2.1 on 2018-08-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='account_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hire_partners',
            name='account_type',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='portfolio_picture',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
