# Generated by Django 2.1 on 2018-08-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_listing',
            name='clients',
            field=models.ManyToManyField(to='django_app.Clients'),
        ),
        migrations.AddField(
            model_name='users',
            name='account_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='users',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='lng',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
