# Generated by Django 2.1 on 2018-08-23 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(default='', max_length=30)),
                ('job_desc', models.TextField(default='')),
                ('job_link', models.URLField(blank=True, default='')),
                ('remote_job', models.BooleanField(default=False)),
                ('posted_time', models.DateTimeField(auto_now_add=True)),
                ('hp_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='django_app.Hire_Partners')),
            ],
        ),
        migrations.RemoveField(
            model_name='clients',
            name='joined_field',
        ),
        migrations.AlterField(
            model_name='clients',
            name='relocate',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='clients',
            name='remote',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='HelloWorld',
        ),
    ]
