# Generated by Django 2.1 on 2018-08-21 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20180821_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=20)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('personal_website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employerfavorites',
            name='employerID',
        ),
        migrations.RemoveField(
            model_name='employerfavorites',
            name='studentID',
        ),
        migrations.RemoveField(
            model_name='joblistings',
            name='employerID',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='employerID',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='studentID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='studentfavorites',
            name='employerID',
        ),
        migrations.RemoveField(
            model_name='studentfavorites',
            name='studentID',
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_app.Users')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('remote', models.BooleanField(default=False)),
                ('relocate', models.BooleanField(default=False)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('codepen', models.URLField(blank=True, null=True)),
                ('portfolio_picture', models.URLField(blank=True, null=True)),
            ],
            bases=('django_app.users',),
        ),
        migrations.CreateModel(
            name='Hire_Partners',
            fields=[
                ('users_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_app.Users')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
            ],
            bases=('django_app.users',),
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='EmployerFavorites',
        ),
        migrations.DeleteModel(
            name='JobListings',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentFavorites',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
