# Generated by Django 2.1 on 2018-09-10 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20180907_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire_partners',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hire_partners',
            name='subscription_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
