# Generated by Django 2.1 on 2018-08-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20180827_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='hire_partners',
            name='account_type',
        ),
        migrations.AddField(
            model_name='job_listing',
            name='clients',
            field=models.ManyToManyField(to='django_app.Clients'),
        ),
        migrations.AddField(
            model_name='users',
            name='account_type',
            field=models.BooleanField(default=False),
        ),
    ]
