# Generated by Django 2.1 on 2018-08-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20180830_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='profession',
            field=models.CharField(default='web developer', max_length=100),
        ),
    ]
