# Generated by Django 2.1 on 2018-09-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20180911_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='portfolio_picture',
            field=models.ImageField(blank=True, default='images/d-user.png', upload_to='images/'),
        ),
    ]
