# Generated by Django 2.1 on 2018-08-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20180815_0547'),
    ]

    operations = [
        migrations.CreateModel(
            name='HirePartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pwd', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
