# Generated by Django 2.1 on 2018-09-06 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_clients_profession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_listing',
            name='clients',
        ),
        migrations.AddField(
            model_name='hire_partners',
            name='subscription_end_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
