# Generated by Django 2.1 on 2018-08-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_auto_20180828_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='profession',
            field=models.CharField(default='web developer', max_length=100),
        ),
    ]
