# Generated by Django 2.1 on 2018-09-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_auto_20180911_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='portfolio_picture',
            new_name='picture',
        ),
    ]
