# Generated by Django 2.1 on 2018-08-16 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_auto_20180816_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='pwd',
            new_name='password',
        ),
    ]
