# Generated by Django 2.1 on 2018-08-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_remove_clients_portfolio_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='lat',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='lng',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
