# Generated by Django 2.1 on 2018-09-13 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_auto_20180912_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire_partners',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hire_partners',
            name='subscription_end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
