# Generated by Django 2.1 on 2018-09-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_auto_20180913_2043'),
        ('django_app', '0005_auto_20180912_1935'),
    ]

    operations = [
    ]
